name: Update README.md Profile Metrics
on:
  # Schedule updates (start of each day)
  schedule:
    - cron: "0 0 * * *"
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
    push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml in upstream for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, metadata  # Base content
          plugin_languages: yes  # Most-used languages

          # Achievements (disable for now; too much clutter)
          # plugin_achievements: yes 
          # plugin_achievements_secrets: no  # Hide the secret (pink) ones
